###################  Microservice base configuration  ###################
spring.application.environment: local

server.port: 8081

###################  MongoDB configuration  ###################
spring.data.mongodb.uri: mongodb://localhost:27017/PortfolioManager

###################  Authentication and Authorization  ###################
auth.enabled: true
auth.jwt.secret: 0SnXhfnVgPK0EZRWfr3tV3NGDvHacT1mSg6ziXtoWhdVdhV5msi7oHDspXAqg5Bx