###################  Microservice base configuration  ###################
spring.application:
  name: portfolio-manager
  version: 0.0.1-SNAPSHOT
  environment: ${ENV}

# default port for HTTP:   80
# default port for HTTPS: 443
server:
  port: 8443
  servlet.context-path: /${spring.application.name}
  ssl:
    enabled: true # enable https
    key-store: classpath:certificate/portfolio-manager.p12
    key-store-password: SECRET_KEYSTORE_PASSWORD
    key-store-type: PKCS12
    key-alias: portfolio-manager

logging.level:
  root: INFO
  org.springframework: INFO
  com.portfolio: INFO

###################  MongoDB configuration  ###################
spring.data.mongodb:
  uri: SECRET_MONGODB_ENDPOINT
  auto-index-creation: true

###################  Authentication and Authorization  ###################
auth.enabled: true
auth.jwt.secret: SECRET_AUTH_SECRET